version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: rq worker --url ${REDIS_URL} ${RQ_QUEUE_NAME}
    volumes:
      - ./data:/app/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
